### ISSUE TITLE
Accessing Etherpad through humhub - Access Denied

### ISSUE THREAD

**Issue by fgrosswig** [humhub-contrib/notes#15]
I activated etherpad on the same machine for humhub via plugin. I setup the etherpad and used the API.key to connect the etherpad server. As soon i like to open an pad i receive an authentication failure due i am not elegible to access this pad. The log shows this part information:

Authentication try failed:{"component":"pad","type":"CLIENT_READY","padId":"g.VpGxYdSwYMvM256B$f63205bd-f1bf-487e-a3ae-950682e67fae_9","sessionID":"null","password":null,"token":"t.IfScFrsqbA6g5kIbqDuY","protocolVersion":2}

the etherpad can be acessed over the listener ip directly and i can open and write in etherpad notes. as soon i like to open a pad through humhub i receive the error. The humhub is reached outside of an url domain.bla.blub/ and the humhub passess the iframe to the local listened IP of the etherpad server http://127.0.0.1:9001

so i guess i am always not elegible to open the etherpad through humhub due the reason i do reach the humhub through domain name and it does not passess it to etherpad???

**Comment by Spirantz** [comment]
Hi! I've searched the web and found quite a few people with the same issue. Etherpad works fine if you visit it directly, however using it through HumHub does not work.

**Comment by websenat** [comment]
+1

**Comment by Alexconquer** [comment]
+1

**Comment by Spiritdude** [comment]
+1

**Comment by Spiritdude** [comment]
Perhaps it would be useful to describe exactly what changes Etherpad/settings.json needs so it works with HumHub (by someone who got it working), because current Etherpad 1.5.7 with the current description how to activate Etherpad the "Notes" do not work, the error as mentioned by the original poster.

**Comment by Spirantz** [comment]
So I finally got it working after messing with a few settings. Set the following in the Etherpad settings.json:
```
//IP and port which etherpad should bind at
"ip": SERVER IP 
"port" 9001
```
Note: Setting the IP to localhost and/or 127.0.0.1 will **NOT** work. Ping your server and use the returned IP address as the binded IP.

Next, go to your HumHub installation > Administration > Modules > Notes > Configuration and set the "URL to Etherpad" as **http://yoursite.com:9001/**. Doing this, you can move your HumHub installation anywhere on your server and still have Etherpad working.

I moved my installation three times to different subdomains and simply changed the URL to Etherpad and never lost connection to the API. 

Simply change http://yoursite.com:9001/ to http://subomdain.yoursite.com:9001/.

**Comment by Spiritdude** [comment]
I defined the "ip", but it made no difference:

[2016-01-15 17:43:20.114] [WARN] message - *Authentication try failed*:{"component":"pad","type":"CLIENT_READY","padId":"g.eUdzhxxxxxxx$18da4a02-xxxxxxxxxxxx","sessionID":"null","password":null,"token":"t.PfXExxxxxxxxxxxxXMD","protocolVersion":2}

and within HH "Notes" it says "You do not have permission to access this pad", what am I missing in settings.json?

**Comment by Spirantz** [comment]
Can you display your settings.json file? Also, in the Config for HH Notes you set it to the domain name and installation folder, not the IP, correct? 

Wrong: http://123.4.5.678:9001/
Correct: http://humhublocation.yoursite.com

**Comment by Spiritdude** [comment]
@Spirantz I've got a bit farther, when I put the http://ip-number:9001/ into the HH Notes config, instead the http://hostname:9001/, some content shows up in the etherpad after selecting it in HH, but it looks like more content of the GUI of etherpad but mixed-up (I see a color wheel selector), but the mixed-up content is not editable. HH Notes configuration reports (as before): "Current Status: API Connection successful!"

Once I created a note it lists as "Could not get note content!", when I click "Open Note" I get the mixed up content ... and bin/run.sh still outputs the same Authentication error. My settings.json is the default from etherpad 1.5.7 (https://github.com/ether/etherpad-lite/blob/develop/settings.json.template) and only "ip": entry edited to reflect the server, otherwise no changes made. Did you enable "users": {} part? I use node v0.10.25, lighttpd/1.4.33. Etherpad works with direct access, but not via HH.

**Comment by websenat** [comment]
Etherpad behind reverse proxy (Nginx/https). HH says "API connection success!". Etherpad works with direct access, but not via HH. 
![hh-notes](https://cloud.githubusercontent.com/assets/6212877/12371933/90b621b8-bc45-11e5-9608-8d58c82e61c7.jpg)

**Comment by thurti** [comment]
same configuration and same problem like @websenat

**Comment by thurti** [comment]
I've found a solution for my configuration (Apache, HH on subdomain).

Since etherpad is loaded through an iframe, it has to be accessed through the same domain/subdomain, otherwise the session cookie set by humhub-notes could not be read. (like stated above)

**Solution** (through reverse proxy):
Place a `.htaccess` file with the following rewrite rule in a directory that is reachable under the same subdomain like humhub (eg. `https://humhub.mydomain.com/etherpad`) and of course replace `YOURPORT` by the port number set in your etherpad settings.json.
```apache
RewriteEngine On
RewriteRule (.*) http://localhost:YOURPORT/$1 [P]
```
The [P] option proxies the request to the given url. This requires the apache module [mod_proxy](http://httpd.apache.org/docs/2.4/mod/mod_proxy.html#forwardreverse).

Then in the humhub settings:
URL to Etherpad: `https://humhub.mydomain.com/etherpad/` 
**Note the trailing slash!**

I guess there are equivalent rewrite/proxy solutions for Nginx or lighttpd.
Hope that helps someone...

**Comment by 3cst4sy** [comment]
Got a working solution for the case running humhub under humhub.domain.com and ehterpad under etherpad.domain.com. There is a missing argument by setting the session cookie for etherpad. On line 72 in controllers/NoteController.php: `setcookie("sessionID", $sessionID, $validUntil, '/', 'domain.com'); // Set a cookie`
A Cookie without 'domain.com' will be only available under the domain + subdomain, where humhub is running.

**Comment by funkycram** [comment]
thanks @3cst4sy , worked for me. Would be nice if this could be integrated in the next release.

**Comment by nicovitt** [comment]
> Got a working solution for the case running humhub under humhub.domain.com and ehterpad under etherpad.domain.com. There is a missing argument by setting the session cookie for etherpad. On line 72 in controllers/NoteController.php: `setcookie("sessionID", $sessionID, $validUntil, '/', 'domain.com'); // Set a cookie`
> A Cookie without 'domain.com' will be only available under the domain + subdomain, where humhub is running.

Just add the missing parameter. In currect Version (1.7.1) you can easily spot the command on line 85 and do something like:
`setcookie("sessionID",` $sessionID, $validUntil, '/', substr(yii\helpers\Url::base(''), 2)); // Set a cookie`

**Comment by luke-** [comment]
@nicovitt Thanks for your contribution. Should I always add that or are there side effects?

**Comment by nicovitt** [comment]
@luke- I don't know exactly what the cookie does. As far as I understood the cookie stores the sessionid from the etherpad-server for the specific pad which is created right before. In our case it works because we host the etherpad-server in a subdomain under the same domain as our platform is accessible from: https://pad.xyz.xyz for the etherpad and https://xyz.xyz for our humhub installation. As the documentation (https://www.php.net/manual/de/function.setcookie.php) says the domain param can be specified to tell which domain the cookie is available for. So I think thes solution should work as it basically tells that the cookie is for the domain of the platform.

**Comment by Akhun-Delar** [comment]
For some reason HumHub stops writing any sessionID cookie as soon as I type in the domain parameter. 

`setcookie("sessionID", $sessionID, $validUntil, '/', 'etherpad.mydomain.com'); // Set a cookie`

**Comment by luke-** [comment]
Thanks!

Should be integrated here: https://github.com/humhub-contrib/notes/commit/e6328c7d430acfb649176cdaf8246b5dcabea485
There is now also support for: https://www.npmjs.com/package/ep_auth_session Plugin
